apiVersion: v1
data:
  encrypted-password: M1hLaVMrNnhoc3pNVXQxNUsrK1ZFdTF1N2dydUFQSnFMbTMxUi92L3htRm05eThDN1kwZFoyTWwzTmsyRlVYR1A4N3dUL1Z1dmtjeGp5cjVob0hHeXJCeGhISGJ0aFUvY29yWUlPU0pnT3M9
  extra: eyJmaXJzdC1sb2dpbiI6WyJ0cnVlIl19
  groups: c3lzdGVtOmFkbWlu
  username: YWRtaW4=
kind: Secret
metadata:
  name: admin
  namespace: oauth-user
type: Opaque
