apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-server
  namespace: fuyao-oauth
  labels:
    application: "oauth-server"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: "oauth-server"
  template:
    metadata:
      labels:
        application: "oauth-server"
    spec:
      serviceAccountName: oauth-server
      containers:
        - name: oauth-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: {{ .Values.config.httpServerConfig.port }}
          args:
            - --configFile=config.json
          volumeMounts:
            {{- if .Values.config.httpServerConfig.enableHttps }}
            - name: oauth-serving-ca
              mountPath: /ssl/ca.pem
              subPath: ca.crt
            - name: oauth-server-server
              readOnly: true
              mountPath: /ssl/server.key
              subPath: tls.key
            - name: oauth-server-server
              readOnly: true
              mountPath: /ssl/server.crt
              subPath: tls.crt
            {{- end }}
            - name: config-volume
              readOnly: true
              subPath: config.json
              mountPath: /config.json
            - name: oauth-jwt-cookie-secret
              readOnly: true
              mountPath: /oauth-jwt.key
              subPath: oauth-jwt.key
            - name: oauth-jwt-cookie-secret
              readOnly: true
              mountPath: /oauth-cookie-sign.key
              subPath: oauth-cookie-sign.key
            - name: oauth-jwt-cookie-secret
              readOnly: true
              mountPath: /oauth-cookie-encrypt.key
              subPath: oauth-cookie-encrypt.key
      volumes:
        {{- if .Values.config.httpServerConfig.enableHttps }}
        - name: oauth-serving-ca
          configMap:
            name: oauth-server-serving-ca
        - name: oauth-server-server
          secret:
            secretName: oauth-server-server
        {{- end }}
        - name: config-volume
          configMap:
            name: oauth-server-config
        - name: oauth-jwt-cookie-secret
          secret:
            secretName: oauth-jwt-cookie-secret
