apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-server-audit-logcfg
  namespace: fuyao-oauth
data:
  oauth-server.yaml: |
    Level: info
    EncoderType: console
    Path: /var/log/oauth-server
    FileName: audit.log
    MaxSize: 20
    MaxBackups: 5
    MaxAge: 30
    LocalTime: false
    Compress: true
    OutMod: both