apiVersion: v1
kind: Secret
metadata:
  name: oauth-jwt-cookie-secret
  namespace: fuyao-oauth
type: Opaque
data:
  oauth-jwt.key: |
    {{ b64enc .Values.config.oauthServerConfig.JWTPrivateKey }}
  oauth-cookie-sign.key: |
    {{ b64enc .Values.config.loginSessionConfig.signingKey }}
  oauth-cookie-encrypt.key: |
    {{ b64enc .Values.config.loginSessionConfig.encryptionKey }}