kind: ServiceAccount
apiVersion: v1
metadata:
  name: oauth-server
  namespace: fuyao-oauth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth-user-role
  namespace: oauth-user
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    # 此处可以根据需要添加其他权限配置，如对 ConfigMap 的权限等
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth-user-rolebinding
  namespace: oauth-user  # RoleBinding 所属的命名空间，这里假设为 oauth-server
subjects:
  - kind: ServiceAccount
    name: oauth-server  # 绑定到的 ServiceAccount 名称，这里假设为 oauth-server
    namespace: fuyao-oauth  # ServiceAccount 所属的命名空间，这里假设为 oauth-server
roleRef:
  kind: Role
  name: oauth-user-role  # 引用的 Role 名称
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth-code-token-role
  namespace: oauth-code-token
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    # 此处可以根据需要添加其他权限配置，如对 ConfigMap 的权限等
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth-code-token-rolebinding
  namespace: oauth-code-token  # RoleBinding 所属的命名空间，这里假设为 oauth-server
subjects:
  - kind: ServiceAccount
    name: oauth-server  # 绑定到的 ServiceAccount 名称，这里假设为 oauth-server
    namespace: fuyao-oauth  # ServiceAccount 所属的命名空间，这里假设为 oauth-server
roleRef:
  kind: Role
  name: oauth-code-token-role  # 引用的 Role 名称
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-auth
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oauth-server-webhook-auth
subjects:
  - kind: ServiceAccount
    name: oauth-server
    namespace: fuyao-oauth
roleRef:
  kind: ClusterRole
  name: webhook-auth
  apiGroup: rbac.authorization.k8s.io