config:
  httpServerConfig:
    port: 9096
    enableHttps: true
    tlsCert: |
      -----BEGIN CERTIFICATE-----
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      -----END CERTIFICATE-----
    tlsKey: |
      -----BEGIN PRIVATE KEY-----
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      -----END PRIVATE KEY-----
    rootCA: |
      -----BEGIN CERTIFICATE-----
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      -----END CERTIFICATE-----

  loginSessionConfig:
    maxSeconds: 7200
    # signingKey和encryptionKey会在openFuyao安装的时候由installer生成并覆盖，输入项应已经base64编码
    signingKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    encryptionKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

  ipProtectorConfig:
    failTimes: "5"
    failDuration: "5m"
    lockDuration: "20m"

  oauthServerConfig:
    authCodeExp: "5m"
    accessTokenExp: "5m"
    refreshTokenExp: "2h"
    # JWTPrivateKey和clientIDSecret会在在openFuyao安装的时候由installer生成并覆盖，输入项应已经base64编码
    JWTPrivateKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    clientIDSecret: | 
      {
        "console": "bG9JOG1FUGFQcmladzdUZERuWkRUNVlSWTVCQjJrYVRWa0puK2RJMHFLdz0=",
        "oauthProxy": "U0VDUkVUU1MK"
      }

images:
  core:
    repository: "harbor.openfuyao.com/openfuyao/oauth-server"
    tag: "latest"
    pullPolicy: "Always"
  busyBox:
    repository: "harbor.openfuyao.com/busybox/busybox"
    tag: "1.36.1"
  kubectl:
    repository: "harbor.openfuyao.com/openfuyao/kubectl-openfuyao"
    tag: "latest"

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 100m
    memory: 200Mi
