config:
  httpServerConfig:
    port: 9096
    enableHttps: true
    tlsCert: |
      -----BEGIN CERTIFICATE-----
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      -----END CERTIFICATE-----
    tlsKey: |
      -----BEGIN PRIVATE KEY-----
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      -----END PRIVATE KEY-----
    rootCA: |
      -----BEGIN CERTIFICATE-----
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      -----END CERTIFICATE-----

  loginSessionConfig:
    maxSeconds: 7200
    # signingKey和encryptionKey会在openFuyao安装的时候由installer生成并覆盖
    signingKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    encryptionKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

  ipProtectorConfig:
    failTimes: "5"
    failDuration: "5m"
    lockDuration: "20m"

  oauthServerConfig:
    authCodeExp: "5m"
    accessTokenExp: "2h"
    # JWTPrivateKey会在在openFuyao安装的时候由installer生成并覆盖
    JWTPrivateKey: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    clientSecret:
      console: "console-password"
      oauthProxy: "SECRETTS"

image:
  repository: "harbor.openfuyao.com/openfuyao/oauth-server"
  tag: "v24.09"
  pullPolicy: "Always"
  digest: "sha256:6b3169dc118fb4c479a6fc4e81653b2c431e906633d786955c739dce69992668"
  busyBox: ""
